### ISSUE TITLE
Tags does'nt seems to work

### ISSUE THREAD

**Issue by PierroB** [benjaminjonard/koillection#378]
Hello, 
First, thank you for the work, you put into this project.
I installed the project via docker and it work fine.
During my testing I encountered some troubles with tags. 

First I defined some tags in "Tag categories". Then I try to tag some items with the same tag label but no tagged items appeared in the tag menu.
There is no visible tag on the object itself neither. When I edited it back, the tag I entered is not visible.

Did I do something wrong or is it a bug ?
Thank you in advance for your help.

**Comment by benjaminjonard** [comment]
Hello,

I'm not sure I understand correctly, but tags categories are only used to classify your tags, they are not tags themselves
(if you have a Blu-ray where you add all actors as tags, you could put them in a  "Actor" category, and do the same for producers etc...)

Tags are created dynamically when you add one to an item. There are 2 cases :
- If you already have created the tag on another item, it should autocomplete (click on the right proposed tag to add it to the list)
- If not, press enter to add it to your tags list and it will be created when you submit the form

https://user-images.githubusercontent.com/20560781/148449721-15309383-f675-46b0-b204-a82224c987b3.mp4

In the video "Book" tag already exists, "New tag" and "New tag 2" are new and are going to be created when submitting the form. "New tag 3" won't be created, because I didn't press enter to add it to the list.

I hope I could help you :slightly_smiling_face:

**Comment by PierroB** [comment]
Ho ! Ok, my bad, I just did'nt understood how it work.
I did'nt catch that you need to press enter for each tags. I just wrote my tags splited by a coma and submit...
Thank you for the explanation
