### ISSUE TITLE
[Feature Request] Show fields in list view

### ISSUE THREAD

**Issue by batu-one** [benjaminjonard/koillection#445]
Right now when viewing a collection in list view, there are 3 columns for each item: Name, Visibility and Actions. It would be nice to have the option to have a column displayed for each custom field too.

For example, I have a rating field, and can now sort by rating, but the rating is not visible in the collection list view, only when going into the item. It we could have this, the overview (and sorting) would be much more useful.

**Comment by benjaminjonard** [comment]
Yes this one of the next feature I want to add. 

I just need to find the best way to implement this because an item can have an infinite number of fields, the list would quickly become unreadable. I'm probably going to add a checkbox for each fields in the collection form so users can choose which ones to display.

**Comment by batu-one** [comment]
Sounds great 😊

**Comment by CorneliousJD** [comment]
I was going to suggest the same thing, love this idea and I think the proposed implementation of having a checkbox next to fields to show them in the column view is a great idea as well.
