### ISSUE TITLE
Improve Loan Table labels

### ISSUE THREAD

**Issue by FernandoLRubio** [benjaminjonard/koillection#499]
The current labels in the loan table are confusing. 

Ago makes no sense as the lending date would be today, and the return date is in the future.

![image](https://user-images.githubusercontent.com/5222515/188301830-910bd676-9e45-447c-b82d-32c091015745.png)

A solution to it, plus adding some extra details, could be the following labeling scheme:

Item | Borrower | Lent on | Return Date | Loan duration | Actions |
|-|-|-|-|-|-|
item name| Borrower Name | Lent Date | Return Date | Week difference of Return date - Lent Date | |

**Comment by benjaminjonard** [comment]
Hello, I changed a few labels based on your suggestions. 

For the "Ago" part, its purpose is to show how much time as passed since you've lent that item and haven't got it back yet (it's a reminder, like you have lent that book 6 month ago maybe its time to get it back).
The label is probably not the best, I'll try to come up with a better one.

The loan duration is only displayed in the "Returned" tab, so after you got he item back.

**Comment by FernandoLRubio** [comment]
Thanks! I think I've found what confused me 
![Uploading Screen Shot 2022-09-08 at 12.21.13.png…]()

**Comment by FernandoLRubio** [comment]
I think I found out what started my confusion with "ago". 

In the form where we loan, it's not clear which date is asking for. I assumed it was asking for the return date, not the loan date.

Having both dates would be amazing, but changing the label to "Loan date" would suffice.

<img width="681" alt="Screen Shot 2022-09-08 at 12 21 13" src="https://user-images.githubusercontent.com/5222515/189185966-0c3af42c-46e8-49b8-98c9-af8821918567.png">

**Comment by benjaminjonard** [comment]
Hi, the last release includes some changes to those labels. Do they make more sense now ?
